const STORAGE_KEY = 'second-brain-thoughts-v1';
const PREFS_KEY = 'second-brain-preferences-v1';
const starterThoughts = [
  { id: crypto.randomUUID(), text: 'Welcome to your second brain. Capture anything here—the rough ideas are often the valuable ones.', type: 'note', pinned: true, completed: false, createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(), aiStatus: 'none' },
  { id: crypto.randomUUID(), text: 'Think about one small workflow I could make easier for other people.', type: 'idea', pinned: false, completed: false, createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(), aiStatus: 'none' }
];
let thoughts = []; let currentView = 'all'; let selectedType = 'note'; let pendingAnalysisId = null; let serverMode = false;
const $ = (selector) => document.querySelector(selector);
const list = $('#thought-list');
const prefs = () => JSON.parse(localStorage.getItem(PREFS_KEY) || '{}');

async function api(path, options = {}) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || `Request failed (${response.status})`); return response.json(); }
function saveLocal() { localStorage.setItem(STORAGE_KEY, JSON.stringify(thoughts)); }
function formatDate(value) { const date = new Date(value); return date.toLocaleDateString(undefined, { month:'short', day:'numeric' }) + ' · ' + date.toLocaleTimeString(undefined, { hour:'numeric', minute:'2-digit' }); }
function statusLabel(thought) { if (thought.aiStatus === 'queued') return 'AI queued'; if (thought.aiStatus === 'processing') return 'AI working'; if (thought.aiStatus === 'completed') return 'AI analyzed'; if (thought.aiStatus === 'failed') return 'AI failed'; return ''; }
function render() {
  const query = $('#search-input').value.trim().toLowerCase();
  let visible = thoughts.filter((thought) => { const matchesView = currentView === 'all' || (currentView === 'inbox' && !thought.completed) || (currentView === 'tasks' && thought.type === 'task') || (currentView === 'ideas' && thought.type === 'idea') || (currentView === 'pinned' && thought.pinned); return matchesView && (!query || thought.text.toLowerCase().includes(query)); });
  visible.sort((a,b) => $('#sort-select').value === 'oldest' ? new Date(a.createdAt)-new Date(b.createdAt) : new Date(b.createdAt)-new Date(a.createdAt));
  list.innerHTML = visible.map((thought) => `<article class="thought ${thought.completed ? 'done' : ''}" data-open-note="${thought.id}">
    <button class="thought-check ${thought.completed ? 'done' : ''}" data-action="complete" data-id="${thought.id}" aria-label="${thought.completed ? 'Mark incomplete' : 'Mark complete'}">${thought.completed ? '✓' : ''}</button>
    <div class="thought-body"><div class="thought-text">${escapeHtml(thought.text)}</div><div class="meta"><span class="tag ${thought.type}">${thought.type}</span><span>${formatDate(thought.createdAt)}</span>${statusLabel(thought) ? `<span class="ai-status ${thought.aiStatus}"><span class="ai-dot">✦</span>${statusLabel(thought)}</span>` : ''}</div></div>
    <div class="thought-tools"><button class="icon-button ${thought.aiStatus === 'completed' || thought.aiStatus === 'processing' || thought.aiStatus === 'queued' ? 'ai-on' : ''}" data-action="open" data-id="${thought.id}" aria-label="Open note">✦</button><button class="icon-button ${thought.pinned ? 'pinned' : ''}" data-action="pin" data-id="${thought.id}" aria-label="${thought.pinned ? 'Unpin' : 'Pin'} thought">⚑</button><button class="icon-button" data-action="delete" data-id="${thought.id}" aria-label="Delete thought">×</button></div>
  </article>`).join('');
  $('#empty-state').classList.toggle('hidden', visible.length > 0); list.classList.toggle('hidden', visible.length === 0);
  $('#all-count').textContent = thoughts.length; $('#inbox-count').textContent = thoughts.filter(t => !t.completed).length; $('#task-count').textContent = thoughts.filter(t => t.type === 'task' && !t.completed).length; $('#idea-count').textContent = thoughts.filter(t => t.type === 'idea').length;
}
function escapeHtml(text) { const div = document.createElement('div'); div.textContent = text; return div.innerHTML; }
function escapeAttr(text) { return escapeHtml(text).replaceAll('"', '&quot;'); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2200); }
function openModal(id) { $('#' + id).classList.remove('hidden'); }
function closeModal(id) { $('#' + id).classList.add('hidden'); }
function showNote(id) {
  const thought = thoughts.find(t => t.id === id); if (!thought) return;
  const analysis = thought.aiAnalysis;
  $('#note-modal-content').innerHTML = `<p class="eyebrow">${thought.type.toUpperCase()}</p><h2 id="note-modal-title">${escapeHtml(thought.text.slice(0, 80))}${thought.text.length > 80 ? '…' : ''}</h2><div class="original-note">${escapeHtml(thought.text)}</div>${analysis ? `<section class="analysis-section"><div class="analysis-heading"><span class="ai-badge">✦</span><h3>AI analysis</h3><span class="analysis-model">${escapeHtml(analysis.model || 'AI')}</span></div><div class="analysis-copy">${formatRichText(analysis.explanation || analysis.summary || '')}</div>${analysis.keyPoints?.length ? `<h4>Key points</h4><ul>${analysis.keyPoints.map(point => `<li>${escapeHtml(point)}</li>`).join('')}</ul>` : ''}${analysis.images?.length ? `<h4>Related images</h4><div class="image-grid">${analysis.images.map(image => `<a href="${escapeAttr(image.url)}" target="_blank" rel="noreferrer"><img src="${escapeAttr(image.imageUrl)}" alt="${escapeAttr(image.title || 'Related image')}" loading="lazy"><span>${escapeHtml(image.title || 'View source')}</span></a>`).join('')}</div>` : ''}${analysis.sources?.length ? `<h4>Sources</h4><div class="source-list">${analysis.sources.map(source => `<a href="${escapeAttr(source.url)}" target="_blank" rel="noreferrer"><span>${escapeHtml(source.title || source.url)}</span><small>${escapeHtml(source.url)}</small></a>`).join('')}</div>` : ''}<div class="usage-footer"><span>Model: ${escapeHtml(analysis.model || 'unknown')}</span><span>In: ${analysis.inputTokens ?? '—'} · Out: ${analysis.outputTokens ?? '—'}</span><span>$${Number(analysis.costUsd || 0).toFixed(6)}</span></div></section>` : `<section class="analysis-empty"><span class="ai-badge">✦</span><h3>${thought.aiStatus === 'failed' ? 'Analysis failed' : thought.aiStatus === 'queued' || thought.aiStatus === 'processing' ? 'Analysis is running…' : 'No AI analysis yet'}</h3><p>${thought.aiError ? escapeHtml(thought.aiError) : 'Select Analyze with AI when creating an Idea or Note.'}</p></section>`}`;
  openModal('note-modal');
}
function formatRichText(text) { return escapeHtml(text).replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>'); }
async function loadThoughts() { try { thoughts = await api('/api/thoughts'); serverMode = true; } catch { thoughts = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || starterThoughts; serverMode = false; } render(); }
async function requestAnalysis(id) { const thought = thoughts.find(t => t.id === id); if (!thought) return; if (!serverMode) { toast('Run server.js to enable AI analysis'); return; } try { const updated = await api(`/api/thoughts/${id}/analyze`, { method:'POST', body: JSON.stringify({}) }); Object.assign(thought, updated); render(); toast('AI analysis queued'); } catch (error) { toast(error.message); } }
async function saveThought(thought, wantsAnalysis) { if (serverMode) { const saved = await api('/api/thoughts', { method:'POST', body:JSON.stringify({ ...thought, requestAnalysis:wantsAnalysis }) }); thoughts.unshift(saved); } else { thoughts.unshift(thought); saveLocal(); } $('#capture-input').value = ''; selectedType = 'note'; document.querySelectorAll('.type-button').forEach(b => b.classList.toggle('selected', b.dataset.type === selectedType)); $('#ai-analysis-input').checked = false; render(); toast(wantsAnalysis ? 'Thought saved; AI analysis queued' : 'Thought captured'); }

document.querySelectorAll('.type-button').forEach((button) => button.addEventListener('click', () => { selectedType = button.dataset.type; document.querySelectorAll('.type-button').forEach(b => b.classList.toggle('selected', b === button)); $('#ai-analysis-input').disabled = selectedType === 'task'; if (selectedType === 'task') $('#ai-analysis-input').checked = false; }));
document.querySelectorAll('.nav-item').forEach((button) => button.addEventListener('click', () => { currentView = button.dataset.view; document.querySelectorAll('.nav-item').forEach(b => b.classList.toggle('active', b === button)); $('#view-title').textContent = { all:'All thoughts', inbox:'Inbox', tasks:'Tasks', ideas:'Ideas', pinned:'Pinned' }[currentView]; render(); }));
$('#capture-form').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('#capture-input'); const text = input.value.trim(); const wantsAnalysis = $('#ai-analysis-input').checked && selectedType !== 'task'; if (!text) return; const thought = { id: crypto.randomUUID(), text, type:selectedType, pinned:false, completed:false, createdAt:new Date().toISOString(), aiStatus:wantsAnalysis ? 'queued' : 'none' }; if (wantsAnalysis && !prefs().skipAnalysisConfirmation) { pendingAnalysisId = thought.id; window.pendingThought = thought; openModal('confirm-modal'); return; } try { await saveThought(thought, wantsAnalysis); } catch (error) { toast(error.message); } });
$('#confirm-analysis-button').addEventListener('click', async () => { const thought = window.pendingThought; if (!thought) return; const skip = $('#never-ask-input').checked; if (skip) localStorage.setItem(PREFS_KEY, JSON.stringify({ ...prefs(), skipAnalysisConfirmation:true })); closeModal('confirm-modal'); window.pendingThought = null; pendingAnalysisId = null; try { await saveThought(thought, true); } catch (error) { toast(error.message); } });
list.addEventListener('click', async (event) => { const actionButton = event.target.closest('[data-action]'); const card = event.target.closest('[data-open-note]'); if (actionButton) { const thought = thoughts.find(t => t.id === actionButton.dataset.id); if (!thought) return; if (actionButton.dataset.action === 'open') { showNote(thought.id); return; } if (actionButton.dataset.action === 'delete') { thoughts = thoughts.filter(t => t.id !== thought.id); if (serverMode) await api(`/api/thoughts/${thought.id}`, { method:'DELETE' }).catch(error => toast(error.message)); else saveLocal(); toast('Thought removed'); render(); return; } if (actionButton.dataset.action === 'complete') thought.completed = !thought.completed; if (actionButton.dataset.action === 'pin') thought.pinned = !thought.pinned; if (serverMode) api(`/api/thoughts/${thought.id}`, { method:'PATCH', body:JSON.stringify(thought) }).catch(error => toast(error.message)); else saveLocal(); render(); return; } if (card) showNote(card.dataset.openNote); });
document.querySelectorAll('[data-close-modal]').forEach(button => button.addEventListener('click', () => closeModal(button.dataset.closeModal)));
$('#search-input').addEventListener('input', render); $('#sort-select').addEventListener('change', render); $('#settings-button').addEventListener('click', async () => { openModal('settings-modal'); try { const status = await api('/api/status'); $('#settings-status').textContent = status.configured ? `Connected · ${status.provider} · ${status.model}` : 'No AI key configured'; } catch { $('#settings-status').textContent = 'Local server is not running'; } });
$('#date-label').textContent = new Date().toLocaleDateString(undefined, { weekday:'long', month:'long', day:'numeric' }).toUpperCase();
async function boot() { await loadThoughts(); setInterval(async () => { if (serverMode) { try { thoughts = await api('/api/thoughts'); render(); } catch {} } }, 2500); }
boot();
