# Generated by Django's migration framework for the initial Second Brain schema.
# Keep this file under version control so every environment creates the same tables.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Thought",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("type", models.CharField(choices=[("note", "Note"), ("task", "Task"), ("idea", "Idea")], default="note", max_length=20)),
                ("pinned", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("selected_context", models.CharField(blank=True, max_length=255, null=True)),
                ("context_status", models.CharField(choices=[("not-checked", "Not checked"), ("needs-selection", "Needs selection"), ("resolved", "Resolved"), ("unresolved", "Unresolved")], default="not-checked", max_length=30)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("completed", "Completed"), ("failed", "Failed")], default="completed", max_length=20)),
                ("summary", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                ("key_points", models.JSONField(blank=True, default=list)),
                ("contexts", models.JSONField(blank=True, default=list)),
                ("related_concepts", models.JSONField(blank=True, default=list)),
                ("related_notes", models.JSONField(blank=True, default=list)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("images", models.JSONField(blank=True, default=list)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                ("cost_usd", models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("thought", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analyses", to="thoughts.thought")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AnalysisJob",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed")], default="queued", max_length=20)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("thought", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analysis_jobs", to="thoughts.thought")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["created_at"]},
        ),
    ]
