# Generated by Django 5.2 on 2026-09-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("thoughts", "0002_thought_context_decision_made")]

    operations = [
        migrations.CreateModel(
            name="NoteConnection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("relationship_type", models.CharField(choices=[("related", "Related"), ("builds_on", "Builds on"), ("example_of", "Example of"), ("contradicts", "Contradicts"), ("follow_up_to", "Follow-up to")], default="related", max_length=30)),
                ("description", models.TextField(blank=True)),
                ("origin", models.CharField(choices=[("manual", "Manual"), ("ai_suggested", "AI suggested"), ("ai_confirmed", "AI confirmed"), ("imported", "Imported")], default="manual", max_length=30)),
                ("status", models.CharField(choices=[("suggested", "Suggested"), ("confirmed", "Confirmed"), ("dismissed", "Dismissed"), ("deleted", "Deleted")], default="confirmed", max_length=20)),
                ("confidence", models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_thought", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_connections", to="thoughts.thought")),
                ("target_thought", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="incoming_connections", to="thoughts.thought")),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddConstraint(
            model_name="noteconnection",
            constraint=models.CheckConstraint(condition=~models.Q(("source_thought", models.F("target_thought"))), name="connection_not_self_referential"),
        ),
        migrations.AddConstraint(
            model_name="noteconnection",
            constraint=models.UniqueConstraint(fields=("source_thought", "target_thought", "relationship_type"), name="unique_directed_connection"),
        ),
    ]
